<a href="https://colab.research.google.com/github/Furqonmz/Data_Engineer/blob/main/Data_types_and_structures_with_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x = 1
print(x)

1

In [ ]:
y = -7,9
print(y)

(-7, 9)

In [ ]:
x=3
y=2

In [ ]:
print(x + y)

5

In [ ]:
print(x-y)

1

In [ ]:
print(x*y)

6

In [ ]:
print(x%y)

1

In [ ]:
print(x//y)

1

In [ ]:
print(x**y)
print(y**0.5)

9
1.4142135623730951

In [ ]:
x=True
print(x)

True

In [ ]:
x=1
y=2

print(x>y)

False

In [ ]:
x = 5
y = 4

if y == 3:
  print('benar')
else:
  print('Salah')

Salah

In [ ]:
x = 'Louis'
y = "Owen"

In [ ]:
z = '''
    Python is a fun programming language.
    It is also a very powerful language for Data Science.
    '''
print(z)

    Python is a fun programming language.
    It is also a very powerful language for Data Science.

In [ ]:
print(x+y)

LouisOwen

In [ ]:
print(x*3)

LouisLouisLouis

In [ ]:
print(x[2:])

uis

In [ ]:
print(x.upper())

LOUIS

In [ ]:
print(x.lower())

louis

In [ ]:
text = 'Python is a fun programming language.It is also a very powerful language for Data Science.'

print(text.split())

['Python', 'is', 'a', 'fun', 'programming', 'language.It', 'is', 'also', 'a', 'very', 'powerful', 'language', 'for', 'Data', 'Science.']

In [ ]:
import numpy as np

In [ ]:
arr_1 = np.array([1,2,3,4])
print(arr_1)

[1 2 3 4]

In [ ]:
arr_mixed_1 = np.array(['a','b',1,2])
print(arr_mixed_1)

['a' 'b' '1' '2']

In [ ]:
mat_1 = np.array([[1,2],[3,4]])
print(mat_1)

[[1 2]
 [3 4]]

In [ ]:
list_angka = [1,2,3]
tuple_1 = (1,2,3)
print(tuple_1)

(1, 2, 3)

In [ ]:
list_angka.append(2)
list_angka

[1, 2, 3, 2]

In [ ]:
tuple_1.append(2) #nilai dalam tuple tidak bisa diubah, cocok untuk mengirim dengan hanya bisa mengakses dan melihat tanpa mengubah

AttributeError: 'tuple' object has no attribute 'append'

In [ ]:
set_1 = {1,2,3,4,4,4,4,4,4}
print(set_1)

{1, 2, 3, 4}

In [ ]:
set_2 = set([4,4,4,4,4,4,5,6,7])
print(set_2)

{4, 5, 6, 7}

In [ ]:
list_3 = [1,2,2,3,4,5,6,6,6,6]
list_3

[1, 2, 2, 3, 4, 5, 6, 6, 6, 6]

In [ ]:
ubah_set = set(list_3)
ubah_set

{1, 2, 3, 4, 5, 6}

In [ ]:
# Let say we want to create a dictionary of test scores for each of the students
score_dict = {'Joe': 70,
              'Thom': 95,
              'Monica': 80,
              'Max': 65
              }
print(score_dict)

{'Joe': 70, 'Thom': 95, 'Monica': 80, 'Max': 65}

In [ ]:
print(score_dict['Joe'])
print(score_dict['Max'])

70
65

In [ ]:
# Mengakses Dictionary

import json

dictionary = {
    "id" : "04",
    "name" : "isya",
    "product_reco" : ['makan kucing', 'makan buaya','aksesoris', [1,2,3,4]]
}
dictionary

{'id': '04',
 'name': 'isya',
 'product_reco': ['makan kucing', 'makan buaya', 'aksesoris', [1, 2, 3, 4]]}

In [ ]:
# Mengakses nilai "1" dalam dictionary

dictionary['product_reco'][3][0]

1

In [ ]:
import pandas as pd

In [ ]:
# Creating DataFrame from Numpy Array

df = pd.DataFrame(np.array([[1,2,3], [4,5,6], [7,8,9]]),
                  columns=['col_a','col_b','col_c'])
df

   col_a  col_b  col_c
0      1      2      3
1      4      5      6
2      7      8      9

In [ ]:
df['col_a'].mean()

np.float64(4.0)

In [ ]:
# Operation sederhana dataframe menggunakan custom function

#function

def nilai_akhir(df):
  nilai = (df['col_a']+df['col_b']+df['col_c'])/3

  return nilai

In [ ]:
df['rata-rata nilai']=df.apply(lambda x : nilai_akhir(x), axis=1)
df

   col_a  col_b  col_c  rata-rata nilai
0      1      2      3              2.0
1      4      5      6              5.0
2      7      8      9              8.0

In [ ]:
# Importing CSV files into a dataframe

import pandas as pd
df.pd.read_csv('nama_file.csv')
df

AttributeError: 'DataFrame' object has no attribute 'pd'

# Intermediate Data Types and Structures with Python

In [ ]:
import pandas as pd
apples = pd.Series([3,2,0,1], name="apples")
print(apples)

0    3
1    2
2    0
3    1
Name: apples, dtype: int64

In [ ]:
oranges = pd.Series([0,3,7,2], name="oranges")
fruit_df = pd.DataFrame({"apples": apples, "oranges": oranges})
print(fruit_df)

   apples  oranges
0       3        0
1       2        3
2       0        7
3       1        2

In [2]:
import pandas as pd

In [3]:
# Data satu kolom
data = [10,20,30,40]
series_data = pd.Series(data)
print(series_data)

0    10
1    20
2    30
3    40
dtype: int64

In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4])
print(arr*2)

[2 4 6 8]

In [6]:
data_json = [
    {"nama" : "Andi", "alamat" : {"kota": "Jakarta", "kode_pos": 12345}},
    {"nama" : "Budi", "alamat" : {"kota": "Bandung", "kode_pos": 54321}}
]

# akses langsung tanpa DataFrame
for item in data_json:
  print(item["nama"], "-", item["alamat"]["kota"])

Andi - Jakarta
Budi - Bandung

In [21]:
class Order:
  def __init__(self, order_id, customer_name, order_date, total_amount):
    self.order_id = order_id
    self.customer_name = customer_name
    self.order_date = order_date
    self.total_amount = total_amount
  def calculate_tax(self):
    tax_rate =  0.1
    return self.total_amount * tax_rate
  def display_order(self):
    print(f"ID: {self.order_id} | Nama: {self.customer_name} | Total: {self.total_amount}")

class OrderProcessor:
  def __init__(self):
    self.order = []
  def add_order(self, order):
    self.order.append(order)
  def calculate_total_revenue(self):
    total = 0
    for order in self.order:
      total += order.total_amount
    return total
  def calculate_total_tax(self):
    total_tax = 0
    for order in self.order:
      total_tax += order.calculate_tax()
    return total_tax

pesanan1 = Order("001", "Budi", "2024-01-01", 100000)
pesanan2 = Order("002", "Ana", "2024-01-01", 290987)
prosesor = OrderProcessor()
prosesor.add_order(pesanan1)
prosesor.add_order(pesanan2)
pesanan1.display_order()
pesanan2.display_order()
print(f"Total Revenue: Rp. {prosesor.calculate_total_revenue()}")
print(f"Total pajak: Rp. {prosesor.calculate_total_tax()}")

ID: 001 | Nama: Budi | Total: 100000
ID: 002 | Nama: Ana | Total: 290987
Total Revenue: Rp. 390987
Total pajak: Rp. 39098.7